[tool.mypy]
exclude = ['^tests/']
strict = true

[tool.pytest.ini_options]
addopts = "--cov=linkup/ --cov-report term-missing"
asyncio_default_fixture_loop_scope = "function"

[tool.coverage.report]
exclude_also = ["raise ValueError", "raise TypeError"]
