[project]
authors = []
dependencies = []
description = ""
name = "linkup-python-sdk"
readme = "README.md"
requires-python = ">=3.9"
version = "0.1.0"

[dependency-groups]
dev = [
  "distlib==0.3.9",
  "filelock==3.18.0",
  "identify==2.6.12",
  "iniconfig==2.1.0",
  "mypy==1.16.1",
  "mypy-extensions==1.1.0",
  "nodeenv==1.9.1",
  "packaging==25.0",
  "pathspec==0.12.1",
  "platformdirs==4.3.8",
  "pluggy==1.6.0",
  "pre-commit==4.2.0",
  "pygments==2.19.2",
  "pytest==8.4.1",
  "pytest-asyncio==1.0.0",
  "pytest-cov==6.2.1",
  "pytest-mock==3.14.1",
  "pytest-socket==0.7.0",
  "pyyaml==6.0.2",
  "setuptools==80.9.0",
  "types-setuptools==80.9.0.20250529",
  "typing-extensions==4.14.0",
  "virtualenv==20.31.2"
]

[tool.mypy]
exclude = ['^tests/', 'venv/', '.venv/']
strict = true

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"

[tool.coverage.report]
exclude_also = ["raise ValueError", "raise TypeError"]

[tool.ruff]
line-length = 100
target-version = "py39"

[tool.ruff.lint]
select = [
  "E", # pycodestyle
  "F", # pyflakes
  "I", # isort
  "S", # flake8-bandit
]

[tool.ruff.lint.extend-per-file-ignores]
"tests/**/*_test.py" = ["S101"] # Use of assert detected

[tool.semantic_release]
version_source = "file"
version_pattern = "pyproject.toml:version = \"{version}\""
commit_parser = "conventional"
tag_format = "v{version}"
commit_message = "{version}\n\nAutomatically generated by python-semantic-release"
major_on_zero = true

[tool.semantic_release.changelog.default_templates]
changelog_file = "CHANGELOG.md"

[tool.semantic_release.commit_parser_options]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]
